[features]
seeds = false
skip-lint = false
[programs.localnet]
solquad = "8jALcgNgPLhR3BLoCpd53xuo2VUqLEfjq8hdpP1L7mYu"

[programs.devnet]
solquad = "8jALcgNgPLhR3BLoCpd53xuo2VUqLEfjq8hdpP1L7mYu"

[registry]
url = "https://api.apr.dev"

[provider.localnet]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
